export const achievements = [
  {
    id: "first-try",
    name: "First Try Hero",
    description: "Complete a task without any mistakes",
    icon: "🎯",
    xp: 10,
    unlocked: false,
  },
  {
    id: "never-give-up",
    name: "Never Give Up",
    description: "Unlock a task after being locked",
    icon: "💪",
    xp: 5,
    unlocked: false,
  },
  { id: "task-master", name: "Task Master", description: "Complete all tasks", icon: "👑", xp: 50, unlocked: false },
  {
    id: "perfect-run",
    name: "Perfect Run",
    description: "Finish all tasks without any lockouts",
    icon: "⭐",
    xp: 100,
    unlocked: false,
  },
  {
    id: "speedrunner",
    name: "Speedrunner",
    description: "Complete all tasks under 5 minutes",
    icon: "⚡",
    xp: 75,
    unlocked: false,
  },
  {
    id: "failure-master",
    name: "Failure Master",
    description: "Get all tasks locked at once",
    icon: "🔥",
    xp: 25,
    unlocked: false,
  },
  {
    id: "double-failure",
    name: "Double Failure",
    description: "Enter the same wrong code twice",
    icon: "🤦",
    xp: 5,
    unlocked: false,
  },
]